<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['mail_retrieval_apop'] = 'APOP';
$lang['mail_retrieval_app_description'] = 'Приложение "Получение почты" может использоваться, чтобы получать почту с внешних POP и IMAP-серверов.';
$lang['mail_retrieval_app_name'] = 'Получение почты';
$lang['mail_retrieval_auto_detect'] = 'Автоопределение';
$lang['mail_retrieval_imap'] = 'IMAP';
$lang['mail_retrieval_keep_on_remote_server'] = 'Оставить на удаленном сервере';
$lang['mail_retrieval_local_username'] = 'Локальный пользователь';
$lang['mail_retrieval_local_username_invalid'] = 'Локальное имя пользователя - инвалид.';
$lang['mail_retrieval_mail_entries'] = 'Почтовые записи';
$lang['mail_retrieval_mail_entry'] = 'Почтовая запись';
$lang['mail_retrieval_mail_server'] = 'Почтовый сервер';
$lang['mail_retrieval_pop3'] = 'POP3';
$lang['mail_retrieval_protocol_invalid'] = 'Протокол является недействительным.';
$lang['mail_retrieval_remote_username'] = 'Удаленное имя пользователя';
$lang['mail_retrieval_server'] = 'Сервер';
$lang['mail_retrieval_server_invalid'] = 'Сервер неверен.';
$lang['mail_retrieval_ssl_mode'] = 'Режим SSL';
