#!/bin/sh

# Add fetchmail user
#-------------------

getent group fetchmail >/dev/null || groupadd -r fetchmail
getent passwd fetchmail >/dev/null || \
    useradd -r -g fetchmail -s /sbin/nologin -c "Fetchmail" fetchmail

# Fetchmail RPM does not stop daemon
#-----------------------------------

killall -q fetchmail >/dev/null 2>&1
