<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['mail_retrieval_apop'] = 'APOP';
$lang['mail_retrieval_app_description'] = 'Aplikacja pobierająca pocztę może być używana do ściągania wiadomości z zewnętrznych serwerów POP i IMAP.';
$lang['mail_retrieval_app_name'] = 'Pobieranie poczty';
$lang['mail_retrieval_auto_detect'] = 'Auto wykrywanie';
$lang['mail_retrieval_imap'] = 'IMAP';
$lang['mail_retrieval_keep_on_remote_server'] = 'Zachowaj na zdalnym serwerze';
$lang['mail_retrieval_local_username'] = 'Lokalna nazwa użytkownika';
$lang['mail_retrieval_local_username_invalid'] = 'Lokalna nazwa użytkownika jest nieprawidłowa.';
$lang['mail_retrieval_mail_entries'] = 'Wpisy maili';
$lang['mail_retrieval_mail_entry'] = 'Wpis maila';
$lang['mail_retrieval_mail_server'] = 'Serwer pocztowy';
$lang['mail_retrieval_pop3'] = 'POP3';
$lang['mail_retrieval_protocol_invalid'] = 'Protokół jest nieprawidłowy.';
$lang['mail_retrieval_remote_username'] = 'Zdalna nazwa użytkownika';
$lang['mail_retrieval_server'] = 'Serwer';
$lang['mail_retrieval_server_invalid'] = 'Serwer jest nieprawidłowy.';
$lang['mail_retrieval_ssl_mode'] = 'Tryb SSL';
